export default {
    one_way: '单程',
    round_trip: '往返',
    flight_search_btn: '搜索',
    Economy: '经济舱',
    Business: '商务舱',
    PremiumEconomy: '高端经济舱',
    First: '头等舱',
    BusinessAndFirst: '商务/头等舱',

    departure: '去程',
    departure_alias: '去程',
    departure_title: '去程：',
    return: '返程',
    return_title: '返程：',
    duration: '总时长',

    stops: '中转',

    btn_confirm: '确认',
    btn_complete: '完成',
    high_on_time_rate: '高准点率',
    sort_by: '排序',
    detail: '详情',

    direct_flights_only: '只看直飞',
    filter_by: '筛选',
    multiple_airline: '多航空公司',
    flight_summary_title: '选择供应商',
    no_search_result_tip1: '哎呀,没有找到航班结果',
    no_search_result_tip2: '请尝试更换筛选项',
    no_search_result_tip3: '没有找到对应的返程结果',
    no_search_result_tip4: '请尝试更换出行日期',
    search_other_flight: '搜索其他航班',
    day: '天',
    new: '新',
    old: '旧',
    sec: '次',
    include_tax: '含税',
    rt_include_tax: '往返含税',
    change_airport: '换机场',
    share_flight: '共享',
    filter_cancel: '清除',
    filter_departure_time: '起飞时间',
    filter_arrive_time: '到达时间',
    filter_airline: '航空公司',
    filter_airport: '起降机场',
    filter_no_limit: '不限',
    filter_dt1: '00:00-06:00',
    filter_dt2: '06:00-12:00',
    filter_dt3: '12:00-18:00',
    filter_dt4: '18:00-24:00',
    filter_at1: '00:00-06:00',
    filter_at2: '06:00-12:00',
    filter_at3: '12:00-18:00',
    filter_at4: '18:00-24:00',
    filter_departure_airport: '起飞机场',
    filter_arrive_airport: '降落机场',
    filter_transfer_airport: '中转机场',
    filter_no_result: '没有合适的航班在此筛选范围内',
    filter_clear: '清空筛选',
    arrive_bottom_tips: '已展示所有航班',
    timeline_show_all: '已显示全部',
    timeline_lowest_price_ota: '最低价来自',
    timeline_timeout_tips1: '航班价格可能发生变化，',
    timeline_timeout_tips2: '将为你刷新以获取最新价格。',
    timeline_change_date_limit: '目前仅支持前后三天日期切换哦，更多日期请返回首页选择。',
    depdate_later_returndate: '去程日期不能晚于返程日期哦',
    returndate_earer_depdate: '返程日期不能早于去程日期哦',
    summary_detail_btn: '详情',
    summary_hide_detail_btn: '收起详情',
    summary_booking: '预订',
    summary_rult_tip: '该行李/退改签规则需进入预订页查看',
    summary_igola_booking: '辅助订购 ',
    summary_ota_booking: '跳转官网订购 ',
    summary_price: '各大平台实时价格',
    summary_footer_tip: '飞呀辅助订购为你提供快捷预订通道，无需跳转到第三方平台。但出票和退改签服务仍由第三方机票服务平台提供。',
    summary_no_result: '暂无平台报价',
    summary_research: '重新搜索',
    summary_timeout_tips1: '航班价格可能发生变化,将为你刷新',
    summary_timeout_tips2: '以获取最新价格',
    summary_quick_login: '动态码登录',
    summary_quick_login_tip: '下单前先花10秒登录账号哦',
    summary_other_login: '其他登录方式',
    summary_setting_password: '设置密码',
    summary_setting_password_tip: '首次登录设置个密码吧',
    summary_register_tip: '点击完成表示阅读并同意',
    summary_third_booking: '跳转第三方订购',
    rule_tip_one: '行李/ 退改签规则＞',
    rule_tip_two: '航司直营  公正退改',
    ota_redirect_tip: '以下供应商需跳转至官网预订',

    member_quick_login: '验证码登录',
    member_login: '密码登录',
    phone: '手机号码',
    phone_email: '手机号码/电子邮箱',
    password: '密码',
    forget_password: '忘记密码',
    validation_code: '验证码',
    validation_code_phone: '短信验证码',
    get_validation_code: '获取验证码',
    resend_validation_code: '重新发送',
    other_ways: '第三方登录',
    login: '登录',
    go_login: '去登录',
    register: '注册',
    sign_up_tips: '没有账号？注册一个',
    sign_in_tips: '已有账号？直接登录',

    sign_up_have_account: '该账号已注册，去登录 >',

    sign_in_account_lock: '帐号异常，请联系客服',
    sign_in_account_wrong: '该帐号无效，请重新输入',
    sign_in_not_phone: '该号码无效，请重新输入',
    invalid_phone_err: '该号码已被绑定',
    sign_in_not_account: '该账号还未注册，去注册 >',
    sign_in_not_password: '您还未设置密码',
    sign_in_code_wrong: '验证码错误',
    sign_in_password_wrong: '密码错误',
    account_manage_auth_reach_limit: '当天发送次数已达上限，请明天再试',
    member_timeout: '请求超时，请稍候再试！',
    server_error: '服务错误',
    repeat_error: '请求过于频繁',

    set_pwd_placeholder: '请设置8-16位密码',
    pwd_warning: '密码为8-16个字符（不包含空格）',
    pwd_same_warning: '新密码不能与旧密码相同哦！',
    pwd_error: '密码不正确',
    set_new_pwd_error: '您已设置密码',
    no_pwd_tip: '该账号还没设置密码',
    pwd_invalid_warning: '密码不符合规范',
    right_pre_tips: '点击注册即同意',
    right_flya: '《注册协议》',
    term_service: '服务条款',
}